# Generated by Django 4.2.24 on 2025-09-22 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('surnom', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=10, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True)),
                ('domicile', models.CharField(blank=True, max_length=200, null=True)),
                ('filiation_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('filiation_mere', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_epouse', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_face', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_longue', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes_creees', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FicheDactyloscopique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(blank=True, max_length=10, null=True)),
                ('corpulance', models.CharField(blank=True, max_length=50, null=True)),
                ('cheveux', models.CharField(blank=True, max_length=50, null=True)),
                ('visage', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnie', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('cin', models.CharField(blank=True, max_length=50, null=True)),
                ('service_militaire', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_epouse', models.CharField(blank=True, max_length=50, null=True)),
                ('motifs', models.TextField(blank=True, null=True)),
                ('date_lieu_arrestation', models.TextField(blank=True, null=True)),
                ('unite_arrestation', models.CharField(blank=True, max_length=50, null=True)),
                ('nrpv', models.CharField(blank=True, max_length=50, null=True)),
                ('par', models.CharField(blank=True, max_length=50, null=True)),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dactyloscopique', to='bio.personne')),
            ],
        ),
        migrations.CreateModel(
            name='FicheAnthropometrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unite_origine', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('arrondissement', models.CharField(blank=True, max_length=100, null=True)),
                ('faits', models.TextField(blank=True, null=True)),
                ('marque_particuliere', models.TextField(blank=True, null=True)),
                ('vehicule_zone_action', models.CharField(blank=True, max_length=200, null=True)),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anthropometrique', to='bio.personne')),
            ],
        ),
    ]
