# Generated by Django 4.2.24 on 2025-09-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_personne_fichedactyloscopique_ficheanthropometrique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheanthropometrique',
            name='lieu_naissance',
        ),
        migrations.AddField(
            model_name='personne',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
