# Generated by Django 4.2.24 on 2025-10-22 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_remove_ficheanthropometrique_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('ajout_fiche', 'Ajout de fiche'), ('suppression_fiche', 'Suppression de fiche')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
    ]
